name: "Release Request"
description: "Request a deployment by specifying the evaluation function, changes, target commit/branch, and test confirmation."
title: "Release Request"
labels:
  - release
  - deployment
assignees: []
body:
  - type: textarea
    id: description_of_changes
    attributes:
      label: Description of changes
      description: "Summarize what is changing and why. Include links to PRs, issues, or changelogs."
      placeholder: |
        - What changed:
        - Why:
        - Related PRs/Issues: #123, #456
      render: markdown
    validations:
      required: true

  - type: input
    id: branch_to_deploy
    attributes:
      label: Branch to deploy
      description: |
        Specify Branch name to deploy.
      placeholder: "e.g., release/2025-09-29"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        ### ⚡ Click the Link Below to Run the Workflow
        
        Clicking the link will take you to the Actions page. You will need to click the **"Run workflow"** button there to start the process.
        
        ## [➡️ Go to Workflow Run Page](https://github.com/lambda-feedback/wolframIsSimilar/blob/main/.github/workflows/production-deploy.yml)