name: "Release Request"
description: "Request a deployment by specifying the evaluation function, changes, target commit/branch, and test confirmation."
title: "Release Request"
labels:
  - release
  - deployment
assignees: []
body:
  - type: textarea
    id: description_of_changes
    attributes:
      label: Description of changes
      description: "Summarize what is changing and why. Include links to PRs, issues, or changelogs."
      placeholder: |
        - What changed:
        - Why:
        - Related PRs/Issues: #123, #456
      render: markdown
    validations:
      required: true

  - type: input
    id: commit_or_branch_to_deploy
    attributes:
      label: Commit or branch to deploy
      description: |
        Specify either a commit hash (recommended for precision) or branch name to deploy.
        
        **To get a commit hash from GitHub:**
        Navigate to the commit in the web interface and copy the full SHA from the commit page.
      placeholder: "e.g., a1b2c3d4e5f6789... or release/2025-09-29"
    validations:
      required: true