name: Deploy Production Version to Lambda Feedback

on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch
      branch:
        description: 'Branch to release from'
        required: true
        type: string
        default: 'main'
jobs:
  deploy:
    uses: lambda-feedback/evaluation-function-workflows/.github/workflows/staging-deploy.yml@deploy-request
    with:
      template-repository-name: 'lambda-feedback/evaluation-function-boilerplate-wolfram'
      build-platforms: 'gcp'
      environment: "production"
      version-bump: ${{ inputs.version-bump }}
      branch: ${{ inputs.branch }}
    secrets:
      aws-key-id: ${{ secrets.LAMBDA_CONTAINER_PIPELINE_AWS_ID }}
      aws-secret-key: ${{ secrets.LAMBDA_CONTAINER_PIPELINE_AWS_SECRET}}
      function-admin-api-key: ${{ secrets.FUNCTION_ADMIN_API_KEY}}
      gcp_credentials: ${{ secrets.GCP_DEPLOY }}
